# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 610a1ea034bdd5be4af594a40bf9213e7c4fecdfe267af9d3e6f1ae6f5495d04e1ac427ebcf3db40b2b98cd82a10fbb445509749cf6f2cd75057dbbfc65b3300

test:
  secret_key_base: 1202675effc08de2227a83bab954d3b338aecfb4f03a73a43d8b1ac153d9a05cf307bb387fb26e18c1a1c35ff0cb26a55dd26892fd8d6fa5a2ec93cd3f95bb7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
